## Arrays

In [1]:
import numpy as np

Global earth average daytime temperatures from http://berkeleyearth.lbl.gov/regions/global-land

In [2]:
baseline_high = 14.48 # 1980
highs = np.array([baseline_high - 0.880, baseline_high - 0.093,
                  baseline_high + 0.105, baseline_high + 0.684])
highs # 1850, 1900, 1950, 2000

array([ 13.6  ,  14.387,  14.585,  15.164])

In [3]:
baseline_low = 3.00
lows = np.array((baseline_low - 0.872, baseline_low - 0.629,
                 baseline_low - 0.126, baseline_low + 0.728))
lows # 1850, 1900, 1950, 2000

array([ 2.128,  2.371,  2.874,  3.728])

In [4]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [5]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

Compare http://www.meteo.psu.edu/~j2n/Ed5_Fig3_6b.JPG to http://www.meteo.psu.edu/~j2n/Ed5_Fig3_6a.JPG

In [6]:
highs.size

4

In [7]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [8]:
highs.item(0)

13.6

In [9]:
highs.item(1)

14.387

In [10]:
highs.item(-1)

15.164

In [11]:
highs.item(0) - lows.item(0)

11.472

In [12]:
highs.item(1) - highs.item(0)

0.7870000000000008

In [13]:
np.diff(highs)

array([ 0.787,  0.198,  0.579])